ansibleCrendential:
    organizationName:   ~
    ansibleServer:
        url:            ~
    credentialName:     ~
    userName:           ~
    becomeUserName:     ~

ansibleCrendentialAnsibleServerToken:         ~
ansibleCrendentialUserPassword:               ~
ansibleCrendentialBecomeUserPassword:         ~
ansibleCrendentialUserPrivateSSHKey:          ~
ansibleCrendentialUserPrivateSSHKeyPassphrase: ~
