
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.13
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml

additional_build_files:
    - src: ansible.cfg
      dest: configs

images:
  base_image:
    name: docker.io/redhat/ubi9:latest


additional_build_steps:
  prepend_base:
    - RUN yum install git -y
